name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: [ubuntu-18.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: Build
      run: ./gradlew build
