name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Checkout
      uses: actions/checkout@v2
    - id: Build
      run: ./gradlew build
