name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: Build
      run: ./gradlew build
